import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const primaryColor: [number, number, number] = [15, 23, 42]; // slate-900
const secondaryColor: [number, number, number] = [100, 116, 139]; // slate-500

const addHeaderAndFooter = (doc: any, title: string) => {
  const brandName = "SHOPNO SONCHOY";
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Header Background
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, doc.internal.pageSize.width, 40, 'F');
  
  // Header Text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(brandName, 14, 20);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text("Secure & Transparent Financial Management", 14, 28);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text("DATE: " + date, doc.internal.pageSize.width - 14, 24, { align: 'right' });

  // Report Title
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 55);
  
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.5);
  doc.line(14, 59, doc.internal.pageSize.width - 14, 59);

  // Footer (Added later on all pages)
  const addFooters = () => {
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
      doc.text(
        `Generated by Shopno Sonchoy System on ${new Date().toLocaleString()} | Page ${i} of ${pageCount}`,
        doc.internal.pageSize.width / 2,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      );
    }
  };
  return addFooters;
};

const formatCurrency = (val: number) => `BDT ${val?.toLocaleString() || 0}`;

export const generateMemberReportPDF = (users: any[]) => {
  const doc = new jsPDF();
  const applyFooters = addHeaderAndFooter(doc, "Member Activity & Balance Report");

  const members = users.filter((u: any) => u.role === 'member');
  
  const rows = members.map((u: any) => [
    u.memberId || '-',
    u.name,
    u.phone || '-',
    formatCurrency(u.balance),
    formatCurrency(u.loanBalance)
  ]);

  autoTable(doc, {
    startY: 70,
    head: [['Member ID', 'Name', 'Phone', 'Total Savings', 'Total Loan Balance']],
    body: rows.length ? rows : [['-', 'No members found', '-', '-', '-']],
    theme: 'grid',
    headStyles: { fillColor: primaryColor, textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 4 },
    alternateRowStyles: { fillColor: [248, 250, 252] }
  });

  applyFooters();
  doc.save(`Member_Report_${new Date().getTime()}.pdf`);
};

export const generateCollectionReportPDF = (deposits: any[]) => {
  const doc = new jsPDF();
  const applyFooters = addHeaderAndFooter(doc, "Collection & Deposit Report");

  const approved = deposits.filter((d: any) => d.status === 'approved');
  
  const rows = approved.map((d: any) => [
    d._id.slice(-6).toUpperCase(),
    new Date(d.date).toLocaleDateString(),
    d.userId?.name || 'Unknown',
    d.method,
    formatCurrency(d.amount)
  ]);

  autoTable(doc, {
    startY: 70,
    head: [['Ref ID', 'Date', 'Member Name', 'Method', 'Amount']],
    body: rows.length ? rows : [['-', '-', 'No approved deposits found', '-', '-']],
    theme: 'grid',
    headStyles: { fillColor: [16, 185, 129], textColor: [255, 255, 255], fontStyle: 'bold' }, // Emerald
    styles: { fontSize: 9, cellPadding: 4 },
    alternateRowStyles: { fillColor: [248, 250, 252] }
  });

  applyFooters();
  doc.save(`Collection_Report_${new Date().getTime()}.pdf`);
};

export const generateLoanReportPDF = (loans: any[]) => {
  const doc = new jsPDF('landscape');
  const applyFooters = addHeaderAndFooter(doc, "Loan Disbursement & Interest Report");

  const rows = loans.map((l: any) => [
    l._id.slice(-6).toUpperCase(),
    new Date(l.requestDate).toLocaleDateString(),
    l.userId?.name || 'Unknown',
    formatCurrency(l.amount),
    `${l.interestRate}%`,
    l.durationMonths,
    formatCurrency(l.amount * (1 + l.interestRate / 100)),
    l.status.toUpperCase()
  ]);

  autoTable(doc, {
    startY: 70,
    head: [['Ref ID', 'Request Date', 'Member Name', 'Principal', 'Interest Rate', 'Duration (Mos)', 'Total Payable', 'Status']],
    body: rows.length ? rows : [['-', '-', '-', 'No loans found', '-', '-', '-', '-']],
    theme: 'grid',
    headStyles: { fillColor: [245, 158, 11], textColor: [255, 255, 255], fontStyle: 'bold' }, // Amber
    styles: { fontSize: 9, cellPadding: 4 },
    alternateRowStyles: { fillColor: [254, 252, 232] }
  });

  applyFooters();
  doc.save(`Loan_Report_${new Date().getTime()}.pdf`);
};

export const generateAuditReportPDF = (ledgers: any[]) => {
  const doc = new jsPDF('landscape');
  const applyFooters = addHeaderAndFooter(doc, "Audit Ledger & Journals");

  const rows = ledgers.map((l: any) => [
    new Date(l.date).toLocaleDateString(),
    l.type.toUpperCase(),
    formatCurrency(l.amount),
    l.description || '-',
    l.referenceId ? l.referenceId.slice(-6).toUpperCase() : '-'
  ]);

  autoTable(doc, {
    startY: 70,
    head: [['Date', 'Type', 'Amount', 'Description', 'Reference ID']],
    body: rows.length ? rows : [['-', '-', 'No ledger entries found', '-', '-']],
    theme: 'grid',
    headStyles: { fillColor: [139, 92, 246], textColor: [255, 255, 255], fontStyle: 'bold' }, // Violet
    styles: { fontSize: 9, cellPadding: 4 },
    alternateRowStyles: { fillColor: [248, 250, 252] }
  });

  applyFooters();
  doc.save(`Audit_Report_${new Date().getTime()}.pdf`);
};
